### ISSUE TITLE
[JENKINS-18242] Publish to Cifs even if build failed

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-cifs-plugin#47]
<p>It would be nice if there was an option to publish to Cifs Share Even if the build fails. <br/>
I use the plugin to Archive out logs. I noticed the Failed build logs were getting skipped.<br/>
CIFS: Current build result is <span class="error">&#91;FAILURE&#93;</span>, not going to run.</p>

<p>I saw <a href="https://issues.jenkins.io/browse/JENKINS-15590" title="Publisher should have an option to always run even if the build failed" class="issue-link" data-issue-key="JENKINS-15590"><del>JENKINS-15590</del></a> for SSH But there does not seem to be an equivalent option for Cifs. </p>

---
<details><summary><i>Originally reported by <a title="Joe Montanari" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jmontana">jmontana</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-18242" target="_blank">Publish to Cifs even if build failed</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by gmcdonald** [comment]
This was fixed and applied in #11 and was included in 0.14 and above.
