### ISSUE TITLE
[JENKINS-48675] Jenkins building unstable but transferring files to network

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-cifs-plugin#75]
<p>CIFS: Connecting from host <span class="error">&#91;xxxxxxxx&#93;</span></p>

<p>CIFS: Connecting with configuration <span class="error">&#91;xxxxxxxx&#93;</span> ...</p>

<p>CIFS: Removing WINS from name resolution</p>

<p>CIFS: Setting response timeout <span class="error">&#91;30,000&#93;</span></p>

<p>CIFS: Setting socket timeout <span class="error">&#91;35,000&#93;</span></p>

<p>CIFS: copy <span class="error">&#91;smb://AWSfolder/qa/Directory/01.Folder/02.Folder/01.Folder/File.xlsx&#93;</span></p>

<p>CIFS: copy <span class="error">&#91;smb://AWSfolder/qa/Directory/01.Folder/02.Folder/01.Folder/File.xlsx&#93;</span></p>

<p>CIFS: copy <span class="error">&#91;smb://AWSfolder/qa/Directory/01.Folder/02.Folder/01.Folder/File.xlsx&#93;</span></p>

<p>CIFS: Disconnecting configuration <span class="error">&#91;xxxxxx&#93;</span> ...</p>

<p>ERROR: Exception when publishing, exception message <span class="error">&#91;Access is denied.&#93;</span></p>

<p>Build step 'Send build artifacts to a windows share' changed build result to UNSTABLE</p>

<p>Finished: UNSTABLE</p>

<p>Does anyone know why I am getting Unstable build and 'Access denied' error even though CIFS is transferring files to my AWS network folder</p>

<p>I am using the service account which have access to AWS\qa and AWS\qa\MyProject</p>

---
<details><summary><i>Originally reported by <a title="Arif Khan" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mkhan73">mkhan73</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-48675" target="_blank">Jenkins building unstable but transferring files to network</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Alex Earl" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2018-04-11T22:28:04+10:00
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by e36422** [comment]
any solution for this ?
